apiVersion: v2
name: cadency
description: Helm chart to deploy the cadency discord bot.
version: 0.2.1
appVersion: "0.5.1"
type: application
maintainers:
  - name: BananikXenos
sources:
  - "https://github.com/BananikXenos/cadency-rs"
home: https://github.com/BananikXenos/cadency-rs
