name: Bump Deno
on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        description: The new Deno version
        type: string
  workflow_call:
    inputs:
      version:
        required: true
        description: The new Deno version
        type: string

env:
  DENO_VERSION_FILE: .denorc

jobs:
  update:
    name: Update Version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Update .denorc
        run: |
          rm $DENO_VERSION_FILE
          echo "${{ inputs.version }}" >> $DENO_VERSION_FILE
          cat $DENO_VERSION_FILE
      - name: Create PR
        uses: peter-evans/create-pull-request@v8
        with:
          token: ${{ secrets.PR_AUTOMATION }}
          title: "Update Deno to version `${{ inputs.version }}`"
          branch: "fix/deno-version-update"
          base: main
          add-paths: |
            ${{ env.DENO_VERSION_FILE }}
          commit-message: "fix(deno): Update Deno to `${{ inputs.version }}`"
          delete-branch: true
          body: This is an automated Pull Request to update the Deno version that is used in the docker image.
          labels: dependencies
          assignees: ${{ github.repository_owner }}
